version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: berlinger-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - berlinger-network

  web:
    image: nginx:alpine
    container_name: berlinger-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - berlinger-network

  db:
    image: mysql:8.0
    container_name: berlinger-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: berlinger_cup
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: berlinger
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"
    networks:
      - berlinger-network

networks:
  berlinger-network:
    driver: bridge

volumes:
  dbdata: 